package edu.icet.coursework.util;

public enum ReportType {
    PRODUCT_CATALOG,
    QTY_SOLD_PER_PRODUCT,
    ALL_USERS_REPORT,
    ALL_SUPPLIERS_REPORT,
    DAILY_SALES_REPORT,
    MONTHLY_SALES_REPORT,
    ANNUAL_SALES_REPORT
}
